version: '3.7'

services:
  app:
    container_name: test_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8081:8080
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true